- name: Install the pip
  apt:
    name:  python3-pip
    state: present

- name: Install the Docker SDK
  pip:
    name: "docker>={{ docker_sdk_version }}"
    state: present

- name: Install docker-compose
  get_url:
    url:  https://github.com/docker/compose/releases/download/{{ docker_compose_version }}/docker-compose-{{ ansible_system }}-{{ ansible_architecture }}  
    dest: /usr/local/bin/docker-compose
    mode: 755
