- name: Add Docker’s official GPG key
  apt_key:
    id:             0EBFCD88
    url:            https://download.docker.com/linux/ubuntu/gpg
    state:          present
    validate_certs: yes

- name: Set up the stable repository
  apt_repository:
    repo:           deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_lsb.codename }} stable
    filename:       docker
    state:          present
    validate_certs: yes

- name: Install the latest version of Docker CE
  apt:
    name:         docker-ce
    state:        latest
    update_cache: yes

- name: Install the pip
  apt:
    name: python3-pip
    state: present

- name: Install the Docker SDK
  pip:
    name: "docker>={{ docker_sdk_version }}"
    state: present

- name: Ensure Docker is running (and enable it at boot)
  service: name=docker state=started enabled=yes
